name: CD - Deploy App & Report

on:
  workflow_run:
    workflows: ["Appium WebdriverIO Tests"]  # Nama workflow CI
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Move APK and Report
        run: |
          mkdir -p /deploy/apk
          mkdir -p /deploy/report
          cp app.apk /deploy/apk/
          cp -r report-excel /deploy/report/
